version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isigk
      POSTGRES_DB: jjj
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
